# -*- coding: utf-8 -*-
"""Jasmine-Talavera-grade8-library-NB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M4Dk23rpr6rkxE4rcAL5KI4wsk0Gfi7T
"""

import firebase_admin
from firebase_admin import credentials, db
# Load the private key
cred = credentials.Certificate("/content/firebase_key.json")
# Initialize the app with your database URL
firebase_admin.initialize_app(cred, {
 "databaseURL": "https://grade8-json-db-default-rtdb.firebaseio.com/"
})
print("Firebase connected successfully!")

import json
with open("/content/books.json") as f:
 book = json.load(f)
print (book)

total_copies = 0
for book_info in book['books']:
    total_copies += book_info['details']['copies']
print(f"Total number of copies of all books in the library: {total_copies}")